Repository ChristmasTest/christmas, pull requests merged in 2023-12, with the labels that each got.

#9 [#7] jest setting
  jest.config.ts
  package-lock.json
  package.json
Labels: 🎄 feat, ⚙️ env

#44 [#19] chromatic, storybook ci
  .github/workflows/chromatic.yml
  .storybook/main.ts
  assets/icons/heart/empty.svg
  assets/icons/heart/full.svg
  assets/icons/heart/half.svg
  components/Gauge/Gauge.stories.tsx
  components/Gauge/Gauge.tsx
  package-lock.json
  package.json
Labels: 🎄 feat

#32 [#17] setting BGM
  .gitignore
  .storybook/main.ts
  assets/images/JingleBell.png
  assets/music/BGM.mp3
  components/Button/JingleBell.tsx
  components/Button/jingleBell.stories.tsx
  global.d.ts
  next.config.js
  package-lock.json
  package.json
  stories/.gitkeep
  styles/GlobalStyle.ts
Labels: 🎄 feat, ⚙️ env

#57 [#49] Share on Facebook
  components/Share/ShareFacebook.stories.tsx
  components/Share/ShareFacebook.tsx
  components/Share/ShareKakao.tsx
  constants/url.ts
Labels: 🎄 feat

#59 [#58] Change SEO,Metadata File for Next13
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
  assets/icons/MainLogo.png
  assets/icons/MainLogo.svg
  components/commons/Meta.tsx
  components/layout/Layout.tsx
  constants/METADATA.ts
  robots.txt
  sitemap.xml
  styles/GlobalStyle.ts
Labels: 🧩 refactor

#61 [#51] Framer-motion
  app/layout.tsx
  app/page.tsx
  components/layout/Layout.tsx
  package-lock.json
  package.json
  styles/motion/PageEffect.ts
  styles/motion/RightSlideEffect.ts
  styles/motion/SpringEffect.ts
Labels: 🎄 feat, ⚙️ env

#63 [#62] Setting MongoDB and Add Schema
  app/api/testcase/[id]/route.ts
  app/api/testcase/route.ts
  libs/db/DBConnect.ts
  libs/db/models/TestCase.ts
  package-lock.json
  package.json
Labels: 🎄 feat, ⚙️ env

#38 [#34] StoryBook for ShareKaKao
  assets/icons/MetaLogo.png
  components/Share/ShareKakao.tsx
  components/Share/SharerKakao.stories.tsx
Labels: 🎄 feat

#46 [#45] Jest Setting
  .eslintrc.json
  jest.config.js
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: 🎄 feat

#66 [#64] modify chormatic actions, attach code coverage actions
  .github/workflows/chromatic.yml
  .github/workflows/codecov.yml
  package.json
Labels: 🎄 feat

#70 [#68] Footer component
  app/page.tsx
  assets/icons/Email.svg
  assets/icons/Instagram.svg
  components/Footer/Footer.tsx
  constants/Footer.ts
  styles/GlobalStyle.ts
Labels: 🎄 feat, 🦌 style, ⚙️ env

#71 [#69] Return Component
  components/Button/Return.tsx
Labels: 🎄 feat, 🦌 style

#53 [#48] Copy page link
  components/CopyUrl/CopyUrl.stories.tsx
  components/CopyUrl/index.tsx
  components/Modal/index.tsx
  package-lock.json
  package.json
Labels: 🎄 feat

#81 [#80] Storybook Error
  components/layout/Layout.tsx
  hooks/useGAPageView.ts
Labels: 😡 bug, 🛠️ fix

#82 [#67] modal component
  .github/workflows/codecov.yml
  app/result/page.tsx
  components/CopyUrl/index.tsx
  components/Modal/index.tsx
Labels: 🎄 feat, 🦌 style

#83 [#75] main page style
  app/page.tsx
  components/Button/JingleBell.tsx
Labels: 🎄 feat, 🦌 style

#87 [#78] Result Page Share Buttons
  app/result/page.tsx
  assets/icons/LogoCopy.png
  assets/icons/LogoFacebook.png
  assets/icons/LogoKakao.png
  components/Share/ShareButtons/index.tsx
  components/Share/ShareFacebook.stories.tsx
  components/Share/ShareFacebook.tsx
  components/Share/ShareKakao.tsx
  components/Share/SharerKakao.stories.tsx
  hooks/useGetURL.ts
Labels: 🎄 feat, 🦌 style

#98 [#97] modify url
  .storybook/theme.ts
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
  constants/METADATA.ts
  constants/url.ts
Labels: 🧩 refactor

#93 [#76] all type page
  app/all/page.tsx
  app/layout.tsx
  app/result/page.tsx
  assets/images/Light.png
  components/Button/JingleBell.tsx
  components/Button/Return.tsx
  components/Card/Type.tsx
  components/Footer/Footer.tsx
  components/Text/ResultType.tsx
  next.config.js
Labels: 🎄 feat

#91 [#89] Loading Event
  app/layout.tsx
  app/loading.tsx
  assets/images/Loading.png
  assets/images/LoadingSpinner.gif
Labels: 🎄 feat

#94 [#86] Result Page Reassign
  app/result/page.tsx
  assets/images/ResultBackgroundImg.png
  components/layout/Layout.tsx
  constants/BreackPoint.ts
  styles/GlobalStyle.ts
Labels: 🦌 style

#103 [#102] category by type
  app/result/page.tsx
  components/Footer/Footer.tsx
  components/Text/CategoryByType.tsx
Labels: 🎄 feat

#104 [#101] MogoDB API
  app/api/testcase/type/[type]/route.ts
  libs/api/index.ts
  package-lock.json
  package.json
Labels: 🎄 feat

#100 [#99] img url
  constants/result.ts
Labels: 🎄 feat

#107 [#106] modify style
  app/all/page.tsx
  app/layout.tsx
  app/loading.tsx
  app/page.tsx
  app/result/page.tsx
  app/robots.ts
  app/sitemap.ts
  app/test/page.tsx
  components/Button/Return.tsx
  components/Card/Type.tsx
  components/CopyUrl/index.tsx
  components/Footer/index.tsx
  components/Gauge/Gauge.tsx
  components/Share/ShareButtons/index.tsx
  components/Text/CategoryByType.tsx
  constants/METADATA.ts
  styles/GlobalStyle.ts
  tsconfig.json
Labels: 🦌 style

#92 [#73] README
  README.md
  assets/icons/Logo.svg
  constants/METADATA.ts
Labels: 🎅🏻 docs

#108 [#105] Add imageURL Column And New Answer Schema
  app/api/testcase/route.ts
  libs/db/models/TestCase.ts
Labels: 🎄 feat

#112 [#111] Server component Allow CORS
  app/api/testcase/[id]/route.ts
  app/api/testcase/route.ts
  app/api/testcase/type/[type]/route.ts
  hooks/useAllowCORS.ts
Labels: 🎄 feat, 🧩 refactor

#110 [#109] Test Page Logic Update
  app/all/page.tsx
  app/page.tsx
  app/result/page.tsx
  app/test/TestResult.ts
  app/test/page.tsx
  components/Button/Answer.tsx
  components/Button/answer.stories.tsx
  constants/result.ts
  constants/url.ts
  libs/api/index.ts
Labels: 🎄 feat, 🛠️ fix

#116 [#115] Add loading before test page
  app/test/page.tsx
Labels: 🎄 feat, 🛠️ fix

#114 [#113] Dynamic Kakao Custom Template
  app/result/page.tsx
  components/Share/ShareButtons/index.tsx
  components/Share/ShareKakao.tsx
Labels: 🎄 feat, 🧩 refactor

#119 [#118] MetaData Img change
  app/layout.tsx
  assets/icons/MainLogo.png
Labels: 🧩 refactor

#121 [#120] Result Title Style
  app/result/page.tsx
Labels: 🦌 style

#123 [#122] Test page style add
  app/test/page.tsx
  components/Button/Answer.tsx
Labels: 🦌 style

#126 [#125] Loading fix, Test Img size
  app/loading.tsx
  app/test/page.tsx
  components/Button/Answer.tsx
Labels: 🧩 refactor

#128 [#127] Add TestPage Suspense
  app/page.tsx
Labels: 🧩 refactor
