Repository ChristmasTest/christmas, pull requests merged in 2023-11, with the labels that each got.

#11 [#6] StoryBook Install
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
Labels: ⚙️ env

#13 [#2] apply GA, hotjar
  .github/auto_assign.yml
  app/components/tracking/GoogleAnalytics.tsx
  app/components/tracking/Hotjar.tsx
  app/hooks/useGAPageView.ts
  app/layout.tsx
  app/libs/gtag.ts
  app/page.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: 🎄 feat

#12 [#4] Share Kakao
  .gitignore
  app/assets/icons/kakaoLogo.png
  app/assets/icons/kakaoLogo.svg
  app/components/Button/SharerKakao.tsx
  app/layout.tsx
  next.config.js
Labels: 🎄 feat

#24 [#18] theme, GlobalStyle Settings
  .gitignore
  .storybook/Logo.svg
  .storybook/manager.js
  .storybook/theme.js
  app/assets/icons/GreenButton.svg
  app/assets/icons/RedButton.svg
  app/hooks/useGAPageView.ts
  app/layout.tsx
  app/styles/GlobalStyle.ts
  app/styles/styled.d.ts
  app/styles/theme.ts
  next.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: 🎄 feat

#27 [#26] Change folder structure
  app/layout.tsx
  assets/icons/GreenButton.svg
  assets/icons/RedButton.svg
  assets/icons/kakaoLogo.png
  assets/icons/kakaoLogo.svg
  components/Button/SharerKakao.tsx
  components/commons/Meta.js
  components/layout/Layout.tsx
  components/tracking/GoogleAnalytics.tsx
  components/tracking/Hotjar.tsx
  constants/METADATA.js
  hooks/useGAPageView.ts
  hooks/useWindowSize.ts
  libs/gtag.ts
  styles/GlobalStyle.ts
  styles/styled.d.ts
  styles/theme.ts
  tsconfig.json
Labels: ⚙️ env

#29 [#28] Js to Tsx
  .storybook/Logo.svg
  .storybook/manager.ts
  .storybook/theme.js
  .storybook/theme.ts
  app/components/commons/Meta.tsx
  app/page.tsx
  assets/icons/MainLogo.svg
  assets/icons/kakaoLogo.svg
  components/Button/SharerKakao.tsx
  components/commons/Meta.tsx
  constants/METADATA.tsx
  package-lock.json
  package.json
Labels: 🧩 refactor, ⚙️ env

#31 [#30] fix grammar error
  app/components/commons/Meta.tsx
  app/page.tsx
Labels: 😡 bug, 🛠️ fix

#33 [#16] sentry
  next.config.js
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.server.config.ts
Labels: 🎄 feat
